---
- hosts: webservers
  vars:
  - warName: javaapp.war
  - warRemotePath: /var/lib/tomcat9/webapps/

  tasks:
  - name: Copy WAR to Remote server
    copy: src=target/{{ warName }} dest={{ warRemotePath }}/{{ warName }} owner=tomcat group=tomcat
